name: periodic
description: Periodic widget (and dialog) to choose a recurring pattern.
version: 1.0.0
homepage: https://github.com/pblinux/periodic
repository: https://github.com/pblinux/periodic

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  customtogglebuttons: ^0.0.5
  flutter_hooks: ^0.15.0
  freezed_annotation: ^0.12.0
  group_radio_button: ^1.0.1
  hooks_riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  freezed: ^0.12.6

flutter: