name: periodic
description: Periodic widget (and dialog) to choose a recurring pattern.
version: 1.0.0
author: pablo@pixela.com.gt
homepage: https://github.com/pblinux/periodic

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  customtogglebuttons:
  flutter_hooks:
  freezed_annotation:
  group_radio_button:
  hooks_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  effective_dart:
  freezed:

flutter: